# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

full_cond_sigmasq <- function(a, b, X, y, beta) {
    .Call(`_bayeslr_full_cond_sigmasq`, a, b, X, y, beta)
}

gibbs_sampler <- function(y, X, m, M, a = 2, b = 1, N = 1000L) {
    .Call(`_bayeslr_gibbs_sampler`, y, X, m, M, a, b, N)
}

